// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAhwN-shfUsj8nXdQpF_gKKyCpNowhLmM0',
    appId: '1:870686722353:web:13f93b506538c126024810',
    messagingSenderId: '870686722353',
    projectId: 'mfbase-5468f',
    authDomain: 'mfbase-5468f.firebaseapp.com',
    storageBucket: 'mfbase-5468f.appspot.com',
    measurementId: 'G-9T5MH551NP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCJ1xCiYRhTNylKuljrfmQet85CQ1R1Yys',
    appId: '1:870686722353:android:2f70ba59070a55fc024810',
    messagingSenderId: '870686722353',
    projectId: 'mfbase-5468f',
    storageBucket: 'mfbase-5468f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAe-2dmOCjAQeGMCyzGN-iDk84Rp8CGzZk',
    appId: '1:870686722353:ios:24db8fb14bbd9251024810',
    messagingSenderId: '870686722353',
    projectId: 'mfbase-5468f',
    storageBucket: 'mfbase-5468f.appspot.com',
    iosBundleId: 'com.example.mfirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAe-2dmOCjAQeGMCyzGN-iDk84Rp8CGzZk',
    appId: '1:870686722353:ios:09a657ea309e2071024810',
    messagingSenderId: '870686722353',
    projectId: 'mfbase-5468f',
    storageBucket: 'mfbase-5468f.appspot.com',
    iosBundleId: 'com.example.mfirebase.RunnerTests',
  );
}
